version: '3.1'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=DEBUG
        - PORT=3000
    env_file: .env
    command: nodemon .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
