version: '3.1'
services:
  test:
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file: .env.test
    command: istanbul cover _mocha -- --exit
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
