version: '3.1'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
        - PORT=3000
    env_file: .env
    command: node --inspect=0.0.0.0:9229 .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/usr/src/app/src
